stages:
  - test
  - build
  - run

include:
  # build and publish Docker image to container registry
  - template: Jobs/Build.gitlab-ci.yml

test:
  stage: test
  image: registry.gitlab.com/mpapp-public/pressroom-base/master:622d44ae18a260d28ec73fee570e238a67783733
  script:
    - yarn install --frozen-lockfile --non-interactive
    - yarn lint
    - yarn test --ci --coverage --reporters=default --reporters=jest-junit
  coverage: '/Statements\s*:\s*(\d+\.\d+)%/'
  artifacts:
    reports:
      junit: junit.xml

run:
  stage: run
  variables:
    PRESSROOM_API_KEY: something-random
    PRESSROOM_ARC_USERNAME: your-user
    PRESSROOM_ARC_PASSWORD: something-random
    PRESSROOM_ARC_API_KEY: something-random
    PRESSROOM_AUTHORIZATION_EMAILS: '@atypon\.com$'
    PRESSROOM_EDIFIX_USERNAME: your-user
    PRESSROOM_EDIFIX_PASSWORD: something-random
    PRESSROOM_GAIA_URL: http://127.0.0.1/template/wileyml
    PRESSROOM_JWT_ROOT: http://127.0.0.1:3000
    PRESSROOM_JWT_ISSUER: 127.0.0.1
    PRESSROOM_LITERATUM_EEO_CLIENT_ID: your-client-id
    PRESSROOM_LITERATUM_EEO_CLIENT_SECRET: something-random
    PRESSROOM_LITERATUM_EEO_URL: https://example.com
    PRESSROOM_LITERATUM_FTPS_HOST: ftps.example.com
    PRESSROOM_LITERATUM_FTPS_PASSWORD: something-random
    PRESSROOM_LITERATUM_FTPS_PREFIX: data
    PRESSROOM_LITERATUM_FTPS_USERNAME: your-username
    PRESSROOM_LITERATUM_SFTP_HOST: sftp.example.com
    PRESSROOM_LITERATUM_SFTP_PEM: base64-encoded-pem
    PRESSROOM_LITERATUM_SFTP_PREFIX: data
    PRESSROOM_LITERATUM_SFTP_USERNAME: your-username
  services:
    - name: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
      alias: pressroom-js
  script:
    - curl --fail http://pressroom-js:5000/
